### ISSUE TITLE
App crash on 7.0

### ISSUE THREAD

**Issue by srivastavavivek1987** [instachat/emoji-library#13]
Please check following error log.

Fatal Exception: java.lang.RuntimeException: Missing type parameter.
       at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(Unknown Source)
       at com.google.gson.reflect.TypeToken.(Unknown Source)
       at br.com.instachat.emojilibrary.util.SharedPreferencesManager$1.(Unknown Source)
       at br.com.instachat.emojilibrary.util.SharedPreferencesManager.pushEmoji(Unknown Source)
       at br.com.instachat.emojilibrary.controller.emoji_pages.FragmentEmojiRecents.onCreateView(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.BackStackRecord.run(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(Unknown Source)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(Unknown Source)
       at android.support.v4.app.FragmentPagerAdapter.setPrimaryItem(Unknown Source)
       at android.support.v4.view.ViewPager.initViewPager(Unknown Source)
       at android.support.v4.view.ViewPager.populate(Unknown Source)
       at android.support.v4.view.ViewPager.onMeasure(Unknown Source)
       at android.view.View.measure(View.java:20136)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
       at android.view.View.measure(View.java:20136)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6285)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
       at android.view.View.measure(View.java:20136)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6285)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
       at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1279)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:659)
       at android.view.View.measure(View.java:20136)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6285)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
       at android.view.View.measure(View.java:20136)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
       at android.view.View.measure(View.java:20136)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6285)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
       at android.view.View.measure(View.java:20136)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6285)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
       at android.view.View.measure(View.java:20136)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6285)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
       at android.view.View.measure(View.java:20136)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6285)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
       at android.view.View.measure(View.java:20136)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6285)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
       at android.view.View.measure(View.java:20136)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6285)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:714)
       at android.view.View.measure(View.java:20136)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2661)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1594)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1863)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1479)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7019)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
       at android.view.Choreographer.doCallbacks(Choreographer.java:709)
       at android.view.Choreographer.doFrame(Choreographer.java:644)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6269)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by edsilfer** [comment]
I believe this is solved on the latest version
